import type { MetadataRoute } from "next"

import { absoluteUrl } from "@/lib/seo"

/**
 * STAGE 9 — `/robots.txt`, generated by Next.js from this file.
 *
 * WHY IT IS NOT PROXIED FROM THE BACKEND: the backend also serves a
 * `/robots.txt`, but it builds the `Sitemap:` line from its OWN
 * `PUBLIC_SITE_URL`. Serving that file here would point crawlers at the
 * backend's sitemap, listing the backend's URLs. robots.txt is per-origin, so
 * this origin states its own rules.
 *
 * `/admin` is disallowed because it is a login-gated panel with nothing
 * crawlable behind it. That is a courtesy, not a control: robots.txt is
 * advisory, so `app/admin/layout.tsx` also sends `noindex, nofollow`, and the
 * backend enforces the actual authorisation. Three layers, because only the
 * last one is a security boundary.
 */
export default function robots(): MetadataRoute.Robots {
	return {
		rules: [
			{
				userAgent: "*",
				allow: "/",
				disallow: "/admin",
			},
		],
		sitemap: absoluteUrl("/sitemap.xml"),
	}
}
