import type { MetadataRoute } from "next"

import { getCategories } from "@/lib/categories"
import { absoluteUrl, categoryPath, newsPath } from "@/lib/seo"
import {
	collectPublishedNews,
	getBackendLastModified,
	toDate,
} from "@/lib/sitemap-data"

/**
 * STAGE 9 — `/sitemap.xml`, generated by Next.js from this file.
 *
 * WHAT IS IN IT: the homepage, every category's page 1, and every published
 * article.
 *
 * WHAT IS DELIBERATELY NOT IN IT:
 *   - `/admin` and everything under it. It is disallowed in robots.txt and
 *     `app/admin/layout.tsx` marks it `noindex, nofollow`; listing it here
 *     would contradict both.
 *   - Paginated category pages (`/category/[slug]/page/2`). A sitemap is for
 *     discovery, and those pages are reachable by crawling page 1. They stay
 *     indexable — each is canonical to itself — they are just not advertised.
 *   - Anything whose existence depends on a backend call that failed: a
 *     partial sitemap is fine, a sitemap full of 404s is not.
 *
 * THREE BACKEND READS, all independent, all fired at once, each with its own
 * fallback: news pages, the category list, and the backend's own sitemap for
 * `<lastmod>` values (the public payloads have no `updatedAt`).
 *
 * `lastModified` is only ever a real timestamp from real data. "Now" would
 * tell crawlers every URL changed on every rebuild, which trains them to stop
 * believing the field.
 */
// Must be a literal — Next.js statically parses this export and cannot resolve an imported identifier. Keep in sync with REVALIDATE_SECONDS in lib/cache.ts.
export const revalidate = 60

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
	const [news, categories, backend] = await Promise.all([
		collectPublishedNews().catch((error: unknown) => {
			console.warn("[sitemap] could not list published news", error)

			return { items: [], truncated: false }
		}),
		getCategories().catch((error: unknown) => {
			console.warn("[sitemap] could not list categories", error)

			return []
		}),
		getBackendLastModified().catch((error: unknown) => {
			console.warn("[sitemap] could not read the backend sitemap", error)

			return {
				news: new Map<string, Date>(),
				categories: new Map<string, Date>(),
			}
		}),
	])

	if (news.truncated) {
		console.warn(
			`[sitemap] article list was truncated at ${news.items.length} entries; the sitemap is incomplete.`,
		)
	}

	// The homepage changes when the newest article does, so it borrows that
	// date instead of inventing one.
	let newest: Date | undefined

	for (const item of news.items) {
		const date = backend.news.get(item.slug) ?? toDate(item.publishedAt)

		if (date && (!newest || date > newest)) {
			newest = date
		}
	}

	const entries: MetadataRoute.Sitemap = [
		{
			url: absoluteUrl("/"),
			...(newest ? { lastModified: newest } : {}),
			changeFrequency: "hourly",
			priority: 1,
		},
	]

	for (const category of categories) {
		const lastModified = backend.categories.get(category.slug)

		entries.push({
			url: absoluteUrl(categoryPath(category.slug)),
			...(lastModified ? { lastModified } : {}),
			changeFrequency: "daily",
			priority: 0.6,
		})
	}

	for (const item of news.items) {
		// Backend `updatedAt` first, the article's own publication date second,
		// nothing at all if neither is usable.
		const lastModified = backend.news.get(item.slug) ?? toDate(item.publishedAt)

		entries.push({
			url: absoluteUrl(newsPath(item.slug)),
			...(lastModified ? { lastModified } : {}),
			// An article is edited shortly after publication, if at all.
			changeFrequency: "weekly",
			priority: 0.8,
		})
	}

	return entries
}
